enum ExprType {
  NUMBER_LITERAL = "NUMBER_LITERAL",
  STRING_LITERAL = "STRING_LITERAL",
  BOOLEAN_LITERAL = "BOOLEAN_LITERAL",
  NULL_LITERAL = "NULL_LITERAL",
  IDENTIFIER = "IDENTIFIER",
  BINARY_EXPR = "BINARY_EXPR",
  UNARY_EXPR = "UNARY_EXPR",
  CALL_EXPR = "CALL_EXPR",
  MEMBER_EXPR = "MEMBER_EXPR",
  ARRAY_EXPR = "ARRAY_EXPR",
  OBJECT_EXPR = "OBJECT_EXPR",
  PROPERTY = "PROPERTY",
  PROGRAM = "PROGRAM",
  STMT = "STMT",

  BLOCK_STATEMENT = "BLOCK_STATEMENT",
  VARIABLE_DECLARATION = "VARIABLE_DECLARATION",
  IF_STATEMENT = "IF_STATEMENT",
  WHILE_STATEMENT = "WHILE_STATEMENT",
  FOR_STATEMENT = "FOR_STATEMENT",
  FUNCTION_DECLARATION = "FUNCTION_DECLARATION",
  RETURN_STATEMENT = "RETURN_STATEMENT",
  BREAK_STATEMENT = "BREAK_STATEMENT",
  CONTINUE_STATEMENT = "CONTINUE_STATEMENT",
  EXPRESSION_STATEMENT = "EXPRESSION_STATEMENT",
  EMPTY_STATEMENT = "EMPTY_STATEMENT",
  THIS_EXPRESSION = "THIS_EXPRESSION",
  NEW_EXPRESSION = "NEW_EXPRESSION",
  CLASS_DECLARATION = "CLASS_DECLARATION",
  FUNCTION_CALL_EXPR = "FUNCTION_CALL_EXPR",
  ASSIGNMENT_EXPR = "ASSIGNMENT_EXPR",

  ARRAY_INIT_EXPR = "ARRAY_INIT_EXPR",
  ARRAY_LITERAL_EXPR = "ARRAY_LITERAL_EXPR",
  DELETE = "DELETE"
}

export default ExprType;
