export enum StmtType {
  VAR_DECLARATION = "VAR_DECLARATION",
  IF_STATEMENT = "IF_DECLARATION",
  EXPRESSION_STATEMENT = "EXPRESSION_DECLARATION",
  BLOCK_STATEMENT = "BLOCK_DECLARATION",
  WHILE_STATEMENT = "WHILE_DECLARATION",
  FUNCTION_STATEMENT = "FUNCITON_DECLARATION",
  FOR_STATEMENT = "FOR_DECLARATION",
  ASSIGNMENT = "ASSIGNMENT",
  FUNCTION_CALL = "FUNCTION_CALL",
}
