enum TokenType {
  // Keywords
  CLASS = "CLASS",
  FUNCTION = "FUNCTION",
  VAR = "VAR",
  IF = "IF",
  ELSE = "ELSE",
  WHILE = "WHILE",
  FOR = "FOR",
  RETURN = "RETURN",
  BREAK = "BREAK",
  CONTINUE = "CONTINUE",
  TRUE = "TRUE",
  FALSE = "FALSE",
  NULL = "NULL",
  THIS = "THIS",
  SUPER = "SUPER",
  IMPORT = "IMPORT",
  EXPORT = "EXPORT",
  NEW = "NEW",
  ATTR = "ATTR",
  METHOD = "METHOD",
  CONST = "CONST",

  // Primitive Types
  INT = "INT",
  FLOAT = "FLOAT",
  STRING = "STRING",
  BOOLEAN = "BOOLEAN",

  // Operators
  PLUS = "PLUS",
  MINUS = "MINUS",
  MULTIPLY = "MULTIPLY",
  DIVIDE = "DIVIDE",
  MODULO = "MODULO",
  ASSIGN = "ASSIGN",
  EQUAL = "EQUAL",
  NOT_EQUAL = "NOT_EQUAL",
  GREATER = "GREATER",
  GREATER_EQUAL = "GREATER_EQUAL",
  LESS = "LESS",
  LESS_EQUAL = "LESS_EQUAL",
  AND = "AND",
  OR = "OR",
  NOT = "NOT",

  // Increment and Decrement
  INCREMENT = "INCREMENT",
  DECREMENT = "DECREMENT",

  // Punctuation and Delimiters
  COMMA = "COMMA",
  DOT = "DOT",
  SEMICOLON = "SEMICOLON",
  COLON = "COLON",
  LEFT_PAREN = "LEFT_PAREN",
  RIGHT_PAREN = "RIGHT_PAREN",
  LEFT_BRACE = "LEFT_BRACE",
  RIGHT_BRACE = "RIGHT_BRACE",
  LEFT_SQUARE_BRACKET = "LEFT_SQUARE_BRACKET",
  RIGHT_SQUARE_BRACKET = "RIGHT_SQUARE_BRACKET",

  // Literals
  IDENTIFIER = "IDENTIFIER",
  NUMBER = "NUMBER",
  STRING_LITERAL = "STRING_LITERAL",
  BOOLEAN_LITERAL = "BOOLEAN_LITERAL",

  // Comments
  SINGLE_LINE_COMMENT = "SINGLE_LINE_COMMENT",
  MULTI_LINE_COMMENT = "MULTI_LINE_COMMENT",

  // End of File
  EOF = "EOF",
}

export default TokenType;
